#!/usr/bin/env bash
# loop from 1 to 10 and display:
#   "Bad luck" for the 4th iteration.
#   "Good luck" for the 8th iteration.
#   "best School" for all other iterations.

n=1
while [ $n -le 10 ]
do
  if [ $n -eq 4 ]
  then
    echo "bad luck"
  elif [ $n -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( n++ ))
done
