#!/usr/bin/env bash
# display numbers from 1 to 20 in addition to:
#   "Bad luck from China" for the 4th iteration.
#   "Bad luck from Japan" for the 9th iteration.
#   "Bad luck from Italy" for the 17th loop iteration.

n=1
while [ $n -le 20 ]
do
  echo "$n"
  case $n in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( n++ ))
done
