#!/usr/bin/env bash
# display the time for 12 hours and 59 minutes:
#   display hours from 0 to 12.
#   display minutes from 1 to 59.

hr=0
while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  mi=1
  while [ $mi -lt 60 ]
  do
    echo "$mi"
    (( mi++ ))
  done
  (( hr++ ))
done
